version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/tools"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/tools"
    schedule:
      interval: "monthly"
